# Generated by Django 4.1.3 on 2022-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=40, null=True)),
                ('gender', models.CharField(help_text='gender', max_length=40, null=True)),
                ('discription', models.CharField(max_length=500, null=True)),
                ('query_image', models.ImageField(null=True, upload_to='image/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
